### ISSUE TITLE
indoor temperature is NaN

### ISSUE THREAD

**Issue by pirateroad** [jagheterfredrik/esphome-rego1000#14]
hi,please why is my value of indoor temperature sign aka NaN...? I use version 3.9.0,other vakues is correct, except this one...
Thanks for you great work...
![Snímek obrazovky 2023-06-22 220316](https://github.com/jagheterfredrik/esphome-rego1000/assets/130125202/a2a67178-c098-4d89-b607-1505ef091490)

**Comment by jagheterfredrik** [comment]
Do you have a indoor thermometer?

**Comment by pirateroad** [comment]
Yes I have

Dne čt 22. 6. 2023 23:13 uživatel Fredrik Gustafsson <
***@***.***> napsal:

**Comment by jagheterfredrik** [comment]
Is it attached to the heat pump or to home assistant?

**Comment by pirateroad** [comment]
Is attached directly to heatpump

Dne pá 23. 6. 2023 6:37 uživatel Fredrik Gustafsson <
***@***.***> napsal:

**Comment by jagheterfredrik** [comment]
I see. The climate sensor is for people without an attached indoor sensor, who instead uses a third party thermometer to control emulate an attached indoor sensor.

Do you have a CAN-bus attached sensor or a two-wire one?

Anyway; in your case I would add a number for 0x0503: HW_ROOM_GT5 or 0x050C: HW_ROOM_TEMP

**Comment by pirateroad** [comment]
It's  IVT  CAN bus LCD sensor , heatpump is Premium line EQ C6

Dne pá 23. 6. 2023 14:26 uživatel Fredrik Gustafsson <
***@***.***> napsal:

**Comment by jagheterfredrik** [comment]
In that case I’d be very interested in some logs (on debug level) if you don’t mind

**Comment by pirateroad** [comment]
> I see. The climate sensor is for people without an attached indoor sensor, who instead uses a third party thermometer to control emulate an attached indoor sensor.
> 
> Do you have a CAN-bus attached sensor or a two-wire one?
> 
> Anyway; in your case I would add a number for 0x0503: HW_ROOM_GT5 or 0x050C: HW_ROOM_TEMP

How to add this into code? Add in rego1000.yaml?

**Comment by pirateroad** [comment]
why is not see "indoor temperature" in my setup?
![Výstřižek](https://github.com/jagheterfredrik/esphome-rego1000/assets/130125202/5b6e1004-7132-4a79-b02d-7e7cb8d922ef)

**Comment by pirateroad** [comment]
[logs_rego1000-v3.9.0_logs.txt](https://github.com/jagheterfredrik/esphome-rego1000/files/11863811/logs_rego1000-v3.9.0_logs.txt)
Here is log 3.9.0. version

**Comment by jagheterfredrik** [comment]
Yes in rego1000.yaml; https://github.com/jagheterfredrik/esphome-rego1000/blob/d48f9474795c7d83debe130887ee9db2d3965495/rego1000.yaml#L50

make another list item there with name indoor temp and $HW_ROOM_GT5 as rego variable
