### ISSUE TITLE
Canbus adresser

### ISSUE THREAD

**Issue by Heativt** [jagheterfredrik/esphome-rego1000#21]
Hej,
Som jag förstår så är det inte canbus adresser i yaml filerna er ut att vara förkorta, vet du/kan du vilka vilka de äkta canbus adresserna är, jobbar med ett eget program till en annan canbus adapter än esphome.
Mvh
Roger

**Comment by jagheterfredrik** [comment]
Här räknas de ut: https://github.com/jagheterfredrik/esphome-rego1000/blob/01155aa2195d4e94771194a4f36143f8717847bb/components/rego1000/rego.h#L77

poll_id gör du en RTR mot, svaret kommer mot recv_id

**Comment by Heativt** [comment]
Hej Fredrik,
Vet inte om jag gör något något fel men har provat med det du skickade med mitt canbus interface.T.ex GT1 (framledning temp) = 022c från v1.12.1 och  2a9 från v.3.14 men ingen verkar ge något vettig värde för migFör 22c och =>048B3FE0 RTR med rec C8B3FE0 ger data 0247 =>18,7 grader men är enligt vp 46,6 graderFör 2A9=>04AA7FE0 RTR med rec CAA7FE0 ger data 01 troligen inte temp.
Misstänker att jag missförstått något kanske men förstår inte vad. Eller så fungerar inte mitt canbuc interface på samma sätt.
MvhRoger 


Skickat från Yahoo Mail för iPad


Den onsdag, januari 10, 2024, 2:33 em, skrev Fredrik Gustafsson ***@***.***>:




Closed #21 as completed.

**Comment by jagheterfredrik** [comment]
Vad har du för pump och version?

**Comment by Heativt** [comment]
Hej
Min pump version är 3.6.0 och är en HE11,Så inser att jag har tagit fel version ( klantigt av mig) innan, med 3.6.0Får jag rätt värden. Har dock ytterligare en fråga, om det är ok,Jag har en andra krets ansluten, som enligt manualen är T1(E12.T1) men hitta inte den vetDu ev. Vilket nummer GTx den har i 3.6.0
Tack för all hjälpRoger 

Skickat från Yahoo Mail för iPad


Den torsdag, januari 11, 2024, 6:41 fm, skrev Fredrik Gustafsson ***@***.***>:




Vad har du för pump och version?

**Comment by jagheterfredrik** [comment]
Intressant! Så du har två värmepumpar ihopkopplade på can?

I så fall skulle jag göra en dump av all CAN-trafik samtidigt som du använder värmepump 1 för att göra en ändring för någon inställning i värmepump 2 (t.ex. ändra varmvatten-program till eko eller komfort), ladda gärna upp här.

**Comment by Heativt** [comment]
Hej Nej jag inte 2 VP kopplade , utan 1 VP som  styr 2 värmeslingor men med olika värmekurvor och cirkulationspumpar och mäter framledningstemp och styr en shunt på värdet.vad förstår så kan man ha upp till 4 slingor, de 2 första finns reda förberedda, om man vill lägga till 2 till så måste man ytterligare HW. 
Skickar med en inspelning av Can bussen i VP.vad jag har listat ut är att ID 0800C270 ger Framledning temp som måste översättas till rätt temp via  NTC tabell .ID 00040270 ger status på cirkulationspumpen för krets 2.
Mvh Roger
    On Friday, January 12, 2024 at 12:03:03 PM GMT+1, Fredrik Gustafsson ***@***.***> wrote:  
 
 


Intressant! Så du har två värmepumpar ihopkopplade på can?

I så fall skulle jag göra en dump av all CAN-trafik samtidigt som du använder värmepump 1 för att göra en ändring för någon inställning i värmepump 2 (t.ex. ändra varmvatten-program till eko eller komfort), ladda gärna upp här.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  
NO    Direction  Time Scale        Frame Type      Frame Format        Frame ID    Length         Data 
0     Receive     12:48:20:722     Data frame     Extended frame     0800c270     2     02 10      
1     Receive     12:48:20:902     Data frame     Extended frame     00080060     1     00      
2     Receive     12:48:20:985     Data frame     Extended frame     00014060     2     00 01      
3     Receive     12:48:21:066     Data frame     Extended frame     0c038060     2     ff ff      
4     Receive     12:48:21:093     Data frame     Extended frame     0c084060     2     00 e4      
5     Receive     12:48:21:663     Data frame     Extended frame     00010060     1     00      
6     Receive     12:48:21:725     Data frame     Extended frame     08010270     2     00 aa      
7     Receive     12:48:22:173     Data frame     Extended frame     0c0ec060     2     00 45      
8     Receive     12:48:22:197     Data frame     Extended frame     0c0f0060     2     03 c4      
9     Receive     12:48:22:222     Data frame     Extended frame     0c000060     2     00 d6      
10    Receive     12:48:22:228     Data frame     Extended frame     000ac430     2     00 d6      
11    Receive     12:48:22:246     Data frame     Extended frame     0c084060     2     00 e4      
12    Receive     12:48:22:327     Data frame     Extended frame     00008060     1     01      
13    Receive     12:48:22:729     Data frame     Extended frame     08014270     2     01 5c      
14    Receive     12:48:22:900     Data frame     Extended frame     00080060     1     00      
15    Receive     12:48:23:006     Data frame     Extended frame     00090270     1     40      
16    Receive     12:48:23:278     Data frame     Extended frame     0c0ec060     2     00 46      
17    Receive     12:48:23:416     Data frame     Extended frame     0c0f0060     2     03 be      
18    Receive     12:48:23:518     Data frame     Extended frame     0c084060     2     00 e4      
19    Receive     12:48:23:828     Data frame     Extended frame     00054270     1     01      
20    Receive     12:48:23:851     Data frame     Extended frame     08018270     2     01 9e      
21    Receive     12:48:24:115     Data frame     Extended frame     08014270     2     01 5b      
22    Receive     12:48:24:347     Data frame     Extended frame     0004c270     1     00      
23    Receive     12:48:24:378     Data frame     Extended frame     0c084060     2     00 e4      
24    Receive     12:48:24:399     Data frame     Extended frame     0c0d0060     1     00      
25    Receive     12:48:24:727     Data frame     Extended frame     0801c270     2     03 13      
26    Receive     12:48:24:911     Data frame     Extended frame     00080060     1     00      
27    Receive     12:48:24:920     Data frame     Extended frame     00090270     1     41      
28    Receive     12:48:25:022     Data frame     Extended frame     00048270     1     01      
29    Receive     12:48:25:468     Data frame     Extended frame     0c0ec060     2     00 47      
30    Receive     12:48:25:510     Data frame     Extended frame     0c0f0060     2     03 b9      
31    Receive     12:48:25:524     Data frame     Extended frame     0c084060     2     00 e4      
32    Receive     12:48:25:545     Data frame     Extended frame     0c0d4060     1     00      
33    Receive     12:48:25:711     Data frame     Extended frame     00044270     1     01      
34    Receive     12:48:25:725     Data frame     Extended frame     08020270     2     03 2d      
35    Receive     12:48:26:000     Data frame     Extended frame     08010270     2     00 a9      
36    Receive     12:48:26:363     Data frame     Extended frame     00040270     1     01      
37    Receive     12:48:26:564     Data frame     Extended frame     0c0ec060     2     00 46      
38    Receive     12:48:26:590     Data frame     Extended frame     0c0f0060     2     03 be      
39    Receive     12:48:26:617     Data frame     Extended frame     0c084060     2     00 e4      
40    Receive     12:48:26:647     Data frame     Extended frame     0c0d8060     1     00      
41    Receive     12:48:26:732     Data frame     Extended frame     08058270     1     01      
42    Receive     12:48:26:911     Data frame     Extended frame     00080060     1     00      
43    Receive     12:48:26:953     Data frame     Extended frame     08000270     2     01 5f      
44    Receive     12:48:27:028     Data frame     Extended frame     0003c270     1     00      
45    Receive     12:48:27:668     Data frame     Extended frame     0c084060     2     00 e4      
46    Receive     12:48:27:700     Data frame     Extended frame     0c0dc060     1     00      
47    Receive     12:48:27:717     Data frame     Extended frame     00038270     1     00      
48    Receive     12:48:27:742     Data frame     Extended frame     0805c270     1     01      
49    Receive     12:48:28:379     Data frame     Extended frame     00034270     1     00      
50    Receive     12:48:28:719     Data frame     Extended frame     08060270     1     01      
51    Receive     12:48:28:774     Data frame     Extended frame     0c0ec060     2     00 47      
52    Receive     12:48:28:796     Data frame     Extended frame     0c0f0060     2     03 b9      
53    Receive     12:48:28:820     Data frame     Extended frame     0c084060     2     00 e4      
54    Receive     12:48:28:848     Data frame     Extended frame     0c0e0060     1     00      
55    Receive     12:48:28:899     Data frame     Extended frame     00080060     1     00      
56    Receive     12:48:29:047     Data frame     Extended frame     00030270     1     00      
57    Receive     12:48:29:728     Data frame     Extended frame     08064270     1     00      
58    Receive     12:48:29:777     Data frame     Extended frame     0002c270     1     01      
59    Receive     12:48:29:862     Data frame     Extended frame     0c0ec060     2     00 46      
60    Receive     12:48:29:893     Data frame     Extended frame     0c0f0060     2     03 be      
61    Receive     12:48:29:914     Data frame     Extended frame     0c084060     2     00 e4      
62    Receive     12:48:29:940     Data frame     Extended frame     0c0e4060     1     00      
63    Receive     12:48:30:142     Data frame     Extended frame     08014270     2     01 5a      
64    Receive     12:48:30:418     Data frame     Extended frame     09fffff0     4     03 00 06 00      
65    Receive     12:48:30:441     Data frame     Extended frame     00028270     1     01      
66    Receive     12:48:30:724     Data frame     Extended frame     08068270     1     01      
67    Receive     12:48:30:903     Data frame     Extended frame     00080060     1     00      
68    Receive     12:48:30:962     Data frame     Extended frame     0c084060     2     00 e4      
69    Receive     12:48:31:000     Data frame     Extended frame     0c0fc060     1     00      
70    Receive     12:48:31:098     Data frame     Extended frame     00070060     1     00      
71    Receive     12:48:31:723     Data frame     Extended frame     0806c270     1     01      
72    Receive     12:48:31:786     Data frame     Extended frame     00050060     1     00      
73    Receive     12:48:32:073     Data frame     Extended frame     0c084060     2     00 e4      
74    Receive     12:48:32:102     Data frame     Extended frame     0c144060     1     00      
75    Receive     12:48:32:477     Data frame     Extended frame     0004c060     1     00      
76    Receive     12:48:32:722     Data frame     Extended frame     08070270     1     00      
77    Receive     12:48:32:896     Data frame     Extended frame     00080060     1     00      
78    Receive     12:48:33:169     Data frame     Extended frame     00034060     1     01      
79    Receive     12:48:33:197     Data frame     Extended frame     0c084060     2     00 e4      
80    Receive     12:48:33:218     Data frame     Extended frame     0c0f4060     1     00      
81    Receive     12:48:33:852     Data frame     Extended frame     08000270     2     01 5e      
82    Receive     12:48:33:894     Data frame     Extended frame     08074270     1     01      
83    Receive     12:48:33:915     Data frame     Extended frame     00030060     2     00 23      
84    Receive     12:48:33:927     Data frame     Extended frame     001d8431     1     01      
85    Receive     12:48:34:268     Data frame     Extended frame     0c0ec060     2     00 45      
86    Receive     12:48:34:294     Data frame     Extended frame     0c0f0060     2     03 c4      
87    Receive     12:48:34:315     Data frame     Extended frame     0c084060     2     00 e4      
88    Receive     12:48:34:342     Data frame     Extended frame     0c0f8060     1     00      
89    Receive     12:48:34:542     Data frame     Extended frame     00028060     1     07      
90    Receive     12:48:34:712     Data frame     Extended frame     08078270     1     00      
91    Receive     12:48:34:874     Data frame     Extended frame     08010270     2     00 a8      
92    Receive     12:48:34:892     Data frame     Extended frame     00080060     1     00      
93    Receive     12:48:35:228     Data frame     Extended frame     00018060     2     00 00      
94    Receive     12:48:35:365     Data frame     Extended frame     0c084060     2     00 e4      
95    Receive     12:48:35:393     Data frame     Extended frame     0c174060     2     00 00      
96    Receive     12:48:35:719     Data frame     Extended frame     08018270     2     01 9d      
97    Receive     12:48:35:746     Data frame     Extended frame     0807c270     1     01      
98    Receive     12:48:35:912     Data frame     Extended frame     00014060     2     00 01      
99    Receive     12:48:36:305     Data frame     Extended frame     0800c270     2     02 0f      
100   Receive     12:48:36:476     Data frame     Extended frame     0c084060     2     00 e4      
101   Receive     12:48:36:504     Data frame     Extended frame     0c004060     2     00 00      
102   Receive     12:48:36:601     Data frame     Extended frame     00010060     1     00      
103   Receive     12:48:36:712     Data frame     Extended frame     09ffc270     2     00 8d      
104   Receive     12:48:36:891     Data frame     Extended frame     00080060     1     00      
105   Receive     12:48:36:911     Data frame     Extended frame     00030270     1     01      
106   Receive     12:48:37:296     Data frame     Extended frame     00008060     1     01      
107   Receive     12:48:37:570     Data frame     Extended frame     0c084060     2     00 e4      
108   Receive     12:48:37:595     Data frame     Extended frame     0c08c060     2     00 aa      
109   Receive     12:48:37:717     Data frame     Extended frame     08000270     2     01 5e      
110   Receive     12:48:37:974     Data frame     Extended frame     00090270     1     41      
111   Receive     12:48:38:349     Data frame     Extended frame     00030270     1     00      
112   Receive     12:48:38:665     Data frame     Extended frame     0c084060     2     00 e4      
113   Receive     12:48:38:709     Data frame     Extended frame     00054270     1     01      
114   Receive     12:48:38:720     Data frame     Extended frame     0c090060     2     00 00      
115   Receive     12:48:38:731     Data frame     Extended frame     08004270     2     02 ec      
116   Receive     12:48:38:914     Data frame     Extended frame     00080060     1     00      
117   Receive     12:48:39:365     Data frame     Extended frame     0004c270     1     00      
118   Receive     12:48:39:712     Data frame     Extended frame     08008270     2     01 39      
119   Receive     12:48:39:767     Data frame     Extended frame     0dffc060     3     02 00 00      
120   Receive     12:48:39:780     Data frame     Extended frame     001cc430     1     01      
121   Receive     12:48:39:794     Data frame     Extended frame     0c084060     2     00 e4      
122   Receive     12:48:40:049     Data frame     Extended frame     00048270     1     01      
123   Receive     12:48:40:731     Data frame     Extended frame     0800c270     2     02 0f      
124   Receive     12:48:40:756     Data frame     Extended frame     00044270     1     01      
125   Receive     12:48:40:859     Data frame     Extended frame     0c0e8060     2     02 19      
126   Receive     12:48:40:889     Data frame     Extended frame     0c084060     2     00 e4      
127   Receive     12:48:40:902     Data frame     Extended frame     00080060     1     00      
128   Receive     12:48:41:423     Data frame     Extended frame     00040270     1     01      
129   Receive     12:48:41:715     Data frame     Extended frame     08010270     2     00 a8      
130   Receive     12:48:41:976     Data frame     Extended frame     0c14c060     2     00 d6      
131   Receive     12:48:42:020     Data frame     Extended frame     0c084060     2     00 e4      
132   Receive     12:48:42:116     Data frame     Extended frame     0003c270     1     00      
133   Receive     12:48:42:716     Data frame     Extended frame     08014270     2     01 5a      
134   Receive     12:48:42:789     Data frame     Extended frame     00038270     1     00      
135   Receive     12:48:42:904     Data frame     Extended frame     00080060     1     00      
136   Receive     12:48:43:063     Data frame     Extended frame     0c0ec060     2     00 45      
137   Receive     12:48:43:091     Data frame     Extended frame     0c084060     2     00 e4      
138   Receive     12:48:43:584     Data frame     Extended frame     00034270     1     00      
139   Receive     12:48:43:760     Data frame     Extended frame     08018270     2     01 9d      
140   Receive     12:48:44:130     Data frame     Extended frame     08010270     2     00 a7      
141   Receive     12:48:44:166     Data frame     Extended frame     0c0f0060     2     03 c4      
142   Receive     12:48:44:191     Data frame     Extended frame     00030270     1     00      
143   Receive     12:48:44:205     Data frame     Extended frame     0c084060     2     00 e4      
144   Receive     12:48:44:716     Data frame     Extended frame     0801c270     2     03 13      
145   Receive     12:48:44:915     Data frame     Extended frame     00080060     1     00      
146   Receive     12:48:44:942     Data frame     Extended frame     0002c270     1     01      
147   Receive     12:48:44:966     Data frame     Extended frame     08018270     2     01 9c      
148   Receive     12:48:45:270     Data frame     Extended frame     0c038060     2     ff ff      
149   Receive     12:48:45:300     Data frame     Extended frame     0c084060     2     00 e4      
150   Receive     12:48:45:540     Data frame     Extended frame     09fffff0     4     03 00 06 00      
151   Receive     12:48:45:559     Data frame     Extended frame     00028270     1     01      
152   Receive     12:48:45:721     Data frame     Extended frame     08020270     2     03 2d      
153   Receive     12:48:45:915     Data frame     Extended frame     00090270     1     40      
154   Receive     12:48:46:031     Data frame     Extended frame     08008270     2     01 3a      
155   Receive     12:48:46:238     Data frame     Extended frame     00070060     1     00      
156   Receive     12:48:46:342     Data frame     Extended frame     0800c270     2     02 10      
157   Receive     12:48:46:376     Data frame     Extended frame     0c0ec060     2     00 46      
158   Receive     12:48:46:395     Data frame     Extended frame     0c0f0060     2     03 be      
159   Receive     12:48:46:424     Data frame     Extended frame     0c000060     2     00 d6      
160   Receive     12:48:46:437     Data frame     Extended frame     000ac430     2     00 d6      
161   Receive     12:48:46:449     Data frame     Extended frame     0c084060     2     00 e4      
162   Receive     12:48:46:713     Data frame     Extended frame     08058270     1     01      
163   Receive     12:48:46:905     Data frame     Extended frame     00080060     1     00      
164   Receive     12:48:46:929     Data frame     Extended frame     00050060     1     00      
165   Receive     12:48:47:468     Data frame     Extended frame     0c084060     2     00 e4      
166   Receive     12:48:47:543     Data frame     Extended frame     0004c060     1     00      
167   Receive     12:48:47:706     Data frame     Extended frame     0805c270     1     01      
168   Receive     12:48:48:176     Data frame     Extended frame     08018270     2     01 9b      
169   Receive     12:48:48:213     Data frame     Extended frame     00034060     1     01      
170   Receive     12:48:48:568     Data frame     Extended frame     0c084060     2     00 e4      
171   Receive     12:48:48:588     Data frame     Extended frame     0c0d0060     1     00      
172   Receive     12:48:48:608     Data frame     Extended frame     001d8431     1     01      
173   Receive     12:48:48:706     Data frame     Extended frame     08060270     1     01      
174   Receive     12:48:48:906     Data frame     Extended frame     00080060     1     00      
175   Receive     12:48:48:917     Data frame     Extended frame     00030060     2     00 23      
176   Receive     12:48:48:927     Data frame     Extended frame     00034270     1     01      
177   Receive     12:48:49:452     Data frame     Extended frame     08008270     2     01 39      
178   Receive     12:48:49:565     Data frame     Extended frame     00028060     1     07      
179   Receive     12:48:49:671     Data frame     Extended frame     0c0ec060     2     00 45      
180   Receive     12:48:49:702     Data frame     Extended frame     0c0f0060     2     03 c4      
181   Receive     12:48:49:713     Data frame     Extended frame     08000270     2     01 5d      
182   Receive     12:48:49:724     Data frame     Extended frame     08064270     1     00      
183   Receive     12:48:49:733     Data frame     Extended frame     0c084060     2     00 e4      
184   Receive     12:48:49:745     Data frame     Extended frame     0c0d4060     1     00      
185   Receive     12:48:50:238     Data frame     Extended frame     00018060     2     00 00      
186   Receive     12:48:50:334     Data frame     Extended frame     00034270     1     00      
187   Receive     12:48:50:375     Data frame     Extended frame     08020270     2     03 2e      
188   Receive     12:48:50:414     Data frame     Extended frame     08008270     2     01 3a      
189   Receive     12:48:50:712     Data frame     Extended frame     08068270     1     01      
190   Receive     12:48:50:769     Data frame     Extended frame     0c084060     2     00 e4      
191   Receive     12:48:50:793     Data frame     Extended frame     0c0d8060     1     00      
192   Receive     12:48:50:900     Data frame     Extended frame     00080060     1     00      
193   Receive     12:48:51:578     Data frame     Extended frame     00014060     2     00 01      
194   Receive     12:48:51:730     Data frame     Extended frame     0806c270     1     01      
195   Receive     12:48:51:870     Data frame     Extended frame     0c084060     2     00 e4      
196   Receive     12:48:51:913     Data frame     Extended frame     0c0dc060     1     00      
197   Receive     12:48:52:255     Data frame     Extended frame     00008060     1     01      
198   Receive     12:48:52:442     Data frame     Extended frame     0800c270     2     02 11      
199   Receive     12:48:52:513     Data frame     Extended frame     08018270     2     01 9a      
200   Receive     12:48:52:724     Data frame     Extended frame     08070270     1     00      
201   Receive     12:48:52:904     Data frame     Extended frame     00080060     1     00      
202   Receive     12:48:52:959     Data frame     Extended frame     00090270     1     40      
203   Receive     12:48:52:980     Data frame     Extended frame     0c084060     2     00 e4      
204   Receive     12:48:52:995     Data frame     Extended frame     0c0e0060     1     00      
205   Receive     12:48:53:421     Data frame     Extended frame     08010270     2     00 a6      
206   Receive     12:48:53:616     Data frame     Extended frame     00054270     1     01      
207   Receive     12:48:53:806     Data frame     Extended frame     08074270     1     01      
208   Receive     12:48:54:067     Data frame     Extended frame     0c084060     2     00 e4      
209   Receive     12:48:54:106     Data frame     Extended frame     0c0e4060     1     00      
210   Receive     12:48:54:264     Data frame     Extended frame     0004c270     1     00

**Comment by jagheterfredrik** [comment]
Kolla vad du får ut på variabel MV_E12_T1_TEMP

**Comment by Heativt** [comment]
Hej det blir rätt värde ,det verkar vara ett NTc värdeMvhRoger 


Skickat från Yahoo Mail för iPad


Den fredag, januari 12, 2024, 6:00 em, skrev Fredrik Gustafsson ***@***.***>:




Kolla vad du får ut på variabel MV_E12_T1_TEMP
