### ISSUE TITLE
Align with 2024.06 OTA config

### ISSUE THREAD

**Issue by gunstr** [jagheterfredrik/esphome-rego1000#22]
@jagheterfredrik There is a breaking change in 2024.06 why the OTA configuration has to be slightly modified in the yaml. See [the release note](https://esphome.io/changelog/2024.6.0#breaking-changes).
I have fixed and tested this in my local installation and can submit a PR if you want, just let me know.

**Comment by jagheterfredrik** [comment]
A PR would be lovely, thank you!
