### ISSUE TITLE
Bootloop expected when not connected to CAN?

### ISSUE THREAD

**Issue by jappish84** [jagheterfredrik/esphome-rego1000#24]
Thanks for creating and sharing this awesome project. I'm trying to set it up using the 3.4 version of this board: https://github.com/MagnusThome/RejsaCAN-ESP32

I have successfully flashed the device using "regorejsa_redacted" config: 
[regorejsa_redacted.txt](https://github.com/user-attachments/files/16401037/regorejsa_redacted.txt)
I have the `components` folder in my `esphome` folder.

The RejsaCAN board uses a SN65HVD230DR CAN chip with pin 1 (D) on the chip connected to GPIO14 on the esp32-s3 and pin 4 (R) from the chip connected to GPIO13 on the esp32-s3.

The config succesfully compiles and flashes, however the esp32-s3 then goes into a bootloop. I've managed to get some logs from it:
[regorejsa_logs.txt](https://github.com/user-attachments/files/16401063/regorejsa_logs.txt)

The issue seems likely due to the `rego1000` component taking too long to complete, causing the watchdog time to trigger and reset the device. 
Is this expected since I don't have the device connected to my heatpump yet (still on the testbench)?

**Comment by jagheterfredrik** [comment]
Not really.. I might be able to try to replicate next week

**Comment by toothrup** [comment]
> Thanks for creating and sharing this awesome project. I'm trying to set it up using the 3.4 version of this board: https://github.com/MagnusThome/RejsaCAN-ESP32
> 
> I have successfully flashed the device using "regorejsa_redacted" config: [regorejsa_redacted.txt](https://github.com/user-attachments/files/16401037/regorejsa_redacted.txt) I have the `components` folder in my `esphome` folder.
> 
> The RejsaCAN board uses a SN65HVD230DR CAN chip with pin 1 (D) on the chip connected to GPIO14 on the esp32-s3 and pin 4 (R) from the chip connected to GPIO13 on the esp32-s3.
> 
> The config succesfully compiles and flashes, however the esp32-s3 then goes into a bootloop. I've managed to get some logs from it: [regorejsa_logs.txt](https://github.com/user-attachments/files/16401063/regorejsa_logs.txt)
> 
> The issue seems likely due to the `rego1000` component taking too long to complete, causing the watchdog time to trigger and reset the device. Is this expected since I don't have the device connected to my heatpump yet (still on the testbench)?

I had similar problems. Slightly different error messages but same boot loop. Tried "everything" without any success. Finally I tried connecting it to my IVT Rego 1000 and behold, everything works!

**Comment by jappish84** [comment]
Really appreciate you testing and confirming, now I know it's expected when no can bus traffic is present and I guess I can assume everything is working.

**Comment by jagheterfredrik** [comment]
I don’t understand why but case closed 🤷‍♂️
