### ISSUE TITLE
Rego 800 Kombimodul 200 AW

### ISSUE THREAD

**Issue by meijer3** [jagheterfredrik/esphome-rego1000#25]
Hi

I have a IVT Kombimodul 200 A/W. I cannot find which board it uses.
Display looks similair. Is there a way to figure this out? The lib is not working directly, to I get some logging (via SPI tho)

I might that I have the rego 800 ? 

```
[21:31:43][D][canbus:069]: received can message (#1) extended can_id=0x9ffc010 size=2
[21:31:43][D][canbus:069]: received can message (#1) extended can_id=0x10000010 size=2
[21:31:44][D][canbus:069]: received can message (#1) extended can_id=0x10004010 size=2
[21:31:44][D][canbus:069]: received can message (#1) extended can_id=0x10008010 size=2
[21:31:44][D][canbus:069]: received can message (#1) extended can_id=0x1000c010 size=2
[21:31:44][D][canbus:069]: received can message (#1) extended can_id=0x10010010 size=2
[21:31:44][D][canbus:069]: received can message (#2) extended can_id=0x9ffc0d0 size=2
[21:31:44][D][canbus:069]: received can message (#1) extended can_id=0x10014010 size=2
[21:31:44][D][canbus:069]: received can message (#1) extended can_id=0x8018010 size=1
[21:31:44][D][canbus:069]: received can message (#1) extended can_id=0x8018030 size=1
[21:31:44][D][canbus:069]: received can message (#1) extended can_id=0x801c010 size=1
[21:31:44][D][canbus:069]: received can message (#1) extended can_id=0x8020010 size=1
```

**Comment by jagheterfredrik** [comment]
It looks likely to be a Rego 800, unfortunately I have no experience with these controllers. It looks easy enough to get the passive sensors going but active control you might need to do additional investigation.

See https://www.varmepumpsforum.com/vpforum/index.php?topic=70203.0 for possible CAN adresses. You can listen to them by using `rego_listen_can_id` like [this](https://github.com/jagheterfredrik/esphome-rego1000/blob/db9c2045bdeb1eab13fa395a433a80c8071f7368/rego1000.yaml#L142). Use sensor for number values and binary_sensor for on/off type stuff.

**Comment by meijer3** [comment]
Yes thanks!
That helped alot. I can read all the values. There is a catch with lookup tables, which complicated the matter quite a bit. To slow cycles so the wifi dropped, but that is due to lack of my c++ skills
![image](https://github.com/user-attachments/assets/8b85378b-9933-4142-ae6e-9ba731d9f781)


I have adjusted your code a bit, not sure if we should check rego800 logic into this repo. But it comes down to 
```
      if (this->lookup_table == "temperature")
      {
        value = get_lookup_celsius[value];
      }
```

Where `get_lookup_celsius` is a vector `std::vector<int> get_lookup_celsius = {1950, 1925, 1900, 1875, 1850, 1825, 1800,...`
### **IOB-kort i värmepumpen (IOB Card in the Heat Pump):**

| CAN Bus Code | English Description    | Signal | Swedish Description | Value |
| ------------ | ---------------------- | ------ | ------------------- | ----- |
| 10000001     | T6, Hot Gas            | Ai1    | T6, Hetgas          | 531   |
| 10004001     | T8, VB-out             | Ai2    | T8, VB-ut           | 570   |
| 10008001     | T9, VB-in              | Ai3    | T9, VB-in           | 572   |
| 1000C001     | T10, Condenser         | Ai4    | T10, Kondensor      | 567   |
| 10010001     | T11, Evaporator        | Ai5    | T11, Förångare      | 575   |
| 10014001     | T12, Inlet Temperature | Ai6    | T12, Insugstemp     | 640   |
| 08018001     | HP (High Pressure)     | Di1    | HP                  | 1     |
| 0801C001     | Motor Protection       | Di2    | Motorskydd          | 1     |
| 08020001     | Motor Protection       | Di3    | Motorskydd          | 1     |
| 08024001     | LP (Low Pressure)      | Di4    | LP                  | 1     |
| 08028001     | Crankcase Heater       | Do1    | Vevhusvärme         | 0     |
| 0802C001     | Fan                    | Do2    | Fläkt               | 0     |
| 08030001     | 4-Way Valve            | Do3    | 4v-ventil           | 0     |
| 08034001     | Heating Cable          | Do4    | Värmekabel          | 0     |
| 08038001     | Compressor             | Do5    | Kompressor          | 0     |
| 1003C001     |                        | Ao1    |                     |       |
| 09FFC001     | Card Version           |        | Kortversion         | 1     |

---

### **IOB-kort i elpannan (IOB Card in the Electric Boiler):**

| CAN Bus Code | English Description                 | Signal | Swedish Description              | Value |     |
| ------------ | ----------------------------------- | ------ | -------------------------------- | ----- | --- |
| 10000010     | T1, Flow Temperature                | Ai1    | T1, Framledning                  | 570   |     |
| 10004010     | T2, Outdoor Temperature             | Ai2    | T2, Utetemp                      | 637   |     |
| 10008010     | T3, DHW (Domestic Hot Water) Temp   | Ai3    | T3, VV-temp                      | 282   |     |
| 1000C010     | T5, Room Temperature                | Ai4    | T5, Rumstemp                     | 1023  |     |
| 10010010     |                                     | Ai5    |                                  | 1023  |     |
| 10014010     |                                     | Ai6    |                                  | 1023  |     |
| 08018010     |                                     | Di1    |                                  | 0     |     |
| 0801C010     |                                     | Di2    |                                  | 0     |     |
| 08020010     |                                     | Di3    |                                  | 0     |     |
| 08024010     | External Control                    | Di4    | Externstyrning                   | 0     |     |
| 08028010     | G1 Circulation Pump, Heating System | Do1    | G1 Cirkpump värmesystem          | 1     |     |
| 0802C010     | G2 Circulation Pump, Heat Carrier   | Do2    | G2 Cirkpump värmebärare          | 1     |     |
| 08030010     | Diverter Valve                      | Do3    | Växelventil                      | 0     |     |
| 08034010     | Shunt Open                          | Do4    | Shunt öppna                      | 0     |     |
| 080D4010     | Interval Control for Shunt Motor    |        | Intervallstyrning av shuntmotorn |       |     |
| 08038010     | Shunt Close                         | Do5    | Shunt stäng                      | 0     |     |
| 080D8010     | Interval Control for Above          |        | Intervallstyrning av ovan        |       |     |
| 1003C010     |                                     | Ao1    |                                  |       |     |
| 09FFC010     | Card Version                        |        | Kortversion                      | 206   |     |
|              |                                     |        |                                  |       |     |

---

### **Tillskottskort (AHB) och effektvakt (Supplementary Card and Power Guard):**

|CAN Bus Code|Signal|Swedish Description|English Description|Value|
|---|---|---|---|---|
|0801C030||Tillskott ramp A|Supplement Ramp A|0|
|10038030||Avläst ström Fas 1|Measured Current Phase 1||
|1003C030||Avläst ström Fas 2|Measured Current Phase 2||
|10040030||Avläst ström Fas 3|Measured Current Phase 3||
|10044030||Inställd huvudsäkring (A)|Set Main Fuse (A)||
|10048030||Strömmarginal (1/10A)|Current Margin (1/10A)||
|1004C030||Tid från utlöst...|Time Since Triggered...||
|10050030||Tid mellan möjliga...|Time Between Possible...||
|10060030||Effektvakt på.|Power Guard On||
|10064030||Matningsspänning (V)|Supply Voltage (V)||
|10068030||Inkopplad elpatroneffekt (1/100kW)|Connected Electric Heater Power (1/100kW)||
|10078030||Utlöst effektvakt|Triggered Power Guard||
|1007C030||Tillskott ramp B|Supplement Ramp B|0|
|09FFC030||Version tillskottskort|Supplement Card Version||
|09FFC050||Version effektvaktskort|Power Guard Card Version||

**Comment by meijer3** [comment]
Oh and my yaml looks like

```yaml
sensor:
  - &temp
    name: T1, Flow Temperature
    rego_listen_can_id: 0x10000010
    platform: rego800
    unit_of_measurement: °C
    device_class: "temperature"
    lookup_table: "temperature"
    state_class: measurement
    accuracy_decimals: 1
    value_factor: .1
    filters:
      - filter_out: -195
  - <<: *temp
    name: T2, Outdoor Temperature
    rego_listen_can_id: 0x10004010
  - <<: *temp
    name: T3, DHW (Domestic Hot Water) Temp
    rego_listen_can_id: 0x10008010

```

**Comment by jagheterfredrik** [comment]
I started porting the dump code to work with spi in some branch if you want inspiration. Happy it works 👍
