### ISSUE TITLE
Wrong data from rego1000 V3.6.0

### ISSUE THREAD

**Issue by ReadyToExplode** [jagheterfredrik/esphome-rego1000#6]
Hi Fredrik, 
Thank you for your great work, this is exactly what I was looking for!👍
I'm experiencing some problems with the data from rego1000 with version 3.6.0.
The outdoor temperature is constantly showing +49.0°C and room dial is going back to -1.6 when trying to adjust from HA. Nothing is changing on the panel of the rego.
I modified your code in my esphome to adapt my setup, maybe that is the problem. I'm using a ESP32-WROOM-32 with a MCP2515 for the can bus communication. 
Or is it different addresses on my version from the one in the yaml file?
I can see you have uploaded the dump files, but I don't find the correct addresses I'm looking for.

Hope you have some ideas!
BR Fredrik

**Comment by jagheterfredrik** [comment]
Did you make a yaml for 3.6.0 or are you using the 1.12.1 one?

**Comment by ReadyToExplode** [comment]
I'm using the 1.12.1. I guess I need to check the addresses from the dump file for 3.6.0 and adjust?

**Comment by jagheterfredrik** [comment]
Exactly! I didn’t bother as I couldn’t test it but essentially look up the number from the 1.12.1 yaml in the 1.12.1 dump and then find the same name in 3.6.0. Please open a PR for others if it works 👍

**Comment by ReadyToExplode** [comment]
Thanks! It works perfectly!
I will try make a pull request when I have access to my computer again.

**Comment by jagheterfredrik** [comment]
@ReadyToExplode That's great! If you're up for sharing (e.g. in the README.md) your hardware setup (i.e. standard ESP32 with external CAN transceiver) as well that'd be awesome.

**Comment by jagheterfredrik** [comment]
@ReadyToExplode I've added 3.6.0 in #8 but Quick Q; does your compressor binary sensor work and if so did you make changes to the rego_listen_can_id? I think the v3.x.x use 0xxxxxx270 rather than 0xxxxxx260

**Comment by jagheterfredrik** [comment]
I’m going to assume it is.
