### ISSUE TITLE
possible error at  editing file rego 1000.yaml

### ISSUE THREAD

**Issue by pirateroad** [jagheterfredrik/esphome-rego1000#9]
Hi, i am very new in esphome, tryin install esphome-rego1000 on DOIT ESP32 DEVKIT V1 , rego1000.yaml display this errors... Please tell me where i am doing wrong...? Thanks for you reply...
![screenshot 2023-04-10 185058](https://user-images.githubusercontent.com/130125202/230950655-724f7bbe-74dc-4ebe-97dd-2b413d710750.png)

**Comment by cjonhammar** [comment]
https://github.com/jagheterfredrik/esphome-rego1000#installation

Make changes to secrets and CAN bus pins in rego1000.yaml, then install it on the ESP32 using

esphome run rego1000-<version>.yaml

you didnt use the correct version of the yaml file, right?

What version do you have?

**Comment by pirateroad** [comment]
I apologize for the late response, i"m little busy...Thanks for you reply, problem solved cleanup esphome directory in HA.... i have question about hardware connection, ESP 32 is connected directly on CAN bus rego, or  using any CAN transceiver aka TJA1050? Power supply ESP32 is realized 12V bus from rego? Thank you for you help...

**Comment by jagheterfredrik** [comment]
You need a CAN transceiver. You can power the ESP from the rego’s 12V but you have to use a step-down to get correct voltage (3V3).

I’m using a [canlite](https://www.tindie.com/products/voltlog/canlite-esp32-can-development-board/) which integrates a step down and a SN65HVD231 transceiver.
